images:
  airflow:
    repository: fugalkev/airflow-aws
    tag: 1.1.1

logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client

secret:
  # Connections
  - envName: "AIRFLOW_CONN_AWS_DEFAULT"
    secretName: af-connections
    secretKey: aws
  - envName: "AIRFLOW_CONN_POSTGRES_DEFAULT"
    secretName: af-connections
    secretKey: postgres
  # Variables
  - envName: "AIRFLOW_VAR_BUCKET"
    secretName: af-variables
    secretKey: bucket
  - envName: "AIRFLOW_VAR_LOGREV_KEY"
    secretName: af-variables
    secretKey: logrev_key
  - envName: "AIRFLOW_VAR_MOVREV_KEY"
    secretName: af-variables
    secretKey: movrev_key
  - envName: "AIRFLOW_VAR_USRPUR_KEY"
    secretName: af-variables
    secretKey: usrpur_key
  - envName: "AIRFLOW_VAR_USRPUR_TABLE"
    secretName: af-variables
    secretKey: usrpur_table
  - envName: "AIRFLOW_VAR_USRPUR_SCHEMA"
    secretName: af-variables
    secretKey: usrpur_schema
  - envName: "AIRFLOW_VAR_USRPUR_QUERY"
    secretName: af-variables
    secretKey: usrpur_query
  - envName: "AIRFLOW_VAR_GLUEJOB"
    secretName: af-variables
    secretKey: gluejob
  - envName: "AIRFLOW_VAR_REGION"
    secretName: af-variables
    secretKey: region
