images:
  airflow:
    repository: fugalkev/myairflow
    tag: 0.0.5
logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client

workers:
  extraVolumeMounts:
    - name: gcp-key
      mountPath: /opt/airflow/secrets/gcp-key
      readOnly: true

  extraVolumes:
    - name: gcp-key
      secret:
        secretName: gcp-key

env:
  - name: "GOOGLE_APPLICATION_CREDENTIALS"
  - value: "/opt/airflow/secrets/gcp-key/credentials.json"

airflow:
  connections:
    - id: google_cloud_sql_default
      type: gcpcloudsqldb
      description: GCP SQL connection
      host: 
      port: 5432
      login: 
      password: 
      schema: 
      extra: |-
        { "instance": "", 
          "location": "us-central1-a",
          "database_type": "postgres" }
    - id: google_cloud_default
      type: google_cloud_platform