CREATE TABLE {{ params.athena_db }}.dim_location AS
SELECT
    CASE
        lr.location
        WHEN 'Alabama' THEN 'AL'
        WHEN 'Alaska' THEN 'AK'
        WHEN 'Arizona' THEN 'AZ'
        WHEN 'Arkansas' THEN 'AR'
        WHEN 'California' THEN 'CA'
        WHEN 'Colorado' THEN 'CO'
        WHEN 'Connecticut' THEN 'CT'
        WHEN 'Delaware' THEN 'DE'
        WHEN 'Florida' THEN 'FL'
        WHEN 'Georgia' THEN 'GA'
        WHEN 'Hawaii' THEN 'HI'
        WHEN 'Idaho' THEN 'ID'
        WHEN 'Illinois' THEN 'IL'
        WHEN 'Indiana' THEN 'IN'
        WHEN 'Iowa' THEN 'IA'
        WHEN 'Kansas' THEN 'KS'
        WHEN 'Kentucky' THEN 'KY'
        WHEN 'Lousiana' THEN 'LA'
        WHEN 'Maine' THEN 'ME'
        WHEN 'Maryland' THEN 'MD'
        WHEN 'Massachussets' THEN 'MA'
        WHEN 'Michigan' THEN 'MI'
        WHEN 'Minnesota' THEN 'MN'
        WHEN 'Mississippi' THEN 'MS'
        WHEN 'Missouri' THEN 'MO'
        WHEN 'Montana' THEN 'MT'
        WHEN 'Nebraska' THEN 'NE'
        WHEN 'Nevada' THEN 'NV'
        WHEN 'New Hampshire' THEN 'NH'
        WHEN 'New Jersey' THEN 'NJ'
        WHEN 'New Mexico' THEN 'NM'
        WHEN 'New York' THEN 'NY'
        WHEN 'North Carolina' THEN 'NC'
        WHEN 'North Dakota' THEN 'ND'
        WHEN 'Ohio' THEN 'OH'
        WHEN 'Oklahoma' THEN 'OK'
        WHEN 'Oregon' THEN 'OR'
        WHEN 'Pensylvania' THEN 'PA'
        WHEN 'Rhode Island' THEN 'RI'
        WHEN 'South Carolina' THEN 'SC'
        WHEN 'South Dakota' THEN 'SD'
        WHEN 'Tennessee' THEN 'TN'
        WHEN 'Texas' THEN 'TX'
        WHEN 'Utah' THEN 'UT'
        WHEN 'Vermont' THEN 'VT'
        WHEN 'Virginia' THEN 'VA'
        WHEN 'Washington' THEN 'WA'
        WHEN 'West Virginia' THEN 'WV'
        WHEN 'Wisconsin' THEN 'WI'
        WHEN 'Wyoming' THEN 'WY'
    END AS id_dim_location,
    lr.location as location,
    CASE
        WHEN lr.location in ('Alaska', 'Arizona', 'California', 'Colorado', 'Hawaii', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Oregon', 'Utah', 'Washington', 'Wyoming') THEN 'west'
        WHEN lr.location in ('Maine', 'New Hampshire', 'Vermont', 'New York', 'Massachussetts', 'Rhode Island', 'Connecticut', 'New Jersey', 'Pensylvania', 'Delaware', 'Maryland', 'Michigan', 'Ohio', 'Indiana', 'Illinois', 'Wisconsin', 'West Virginia ', 'Virginia', 'North Carolina ', 'Tennessee', 'Kentucky', 'South Carolina ', 'Georgia', 'Alabama', 'Mississippi', 'Florida') THEN 'east'
        ELSE 'center'
    END AS region
FROM
    {{ params.athena_db }}.log_reviews lr
GROUP BY
    lr.location;